version: "3.8"

services:
    php:
        container_name: php
        build: 
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
              - SSMTP_ROOT=${SSMTP_ROOT}
              - SSMTP_MAILHUB=${SSMTP_MAILHUB}
              - SSMTP_AUTH_USER=${SSMTP_AUTH_USER}
              - SSMTP_AUTH_PASS=${SSMTP_AUTH_PASS}
              - SSMTP_AUTH_METHOD=${SSMTP_AUTH_METHOD}
              - SSMTP_USE_TLS=${SSMTP_USE_TLS}
              - SSMTP_USE_STARTTLS=${SSMTP_USE_STARTTLS}
              - SSMTP_HOSTNAME=${SSMTP_HOSTNAME}
              - SSMTP_FROM_LINE_OVERRIDE=${SSMTP_FROM_LINE_OVERRIDE}
        networks:
            - camagru-network
        depends_on:
            - mysql
            - phpmyadmin
        env_file: .env
        ports:
            - "8001:80"
        restart: on-failure

    mysql:
        image: mysql:8.4.0
        container_name: mysql
        build: 
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        volumes:
            - mysql_volume:/var/lib/mysql
        networks:
            - camagru-network
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            USER_ID_1: ${USER_ID_1} # only for portfolio demo
            USER_ID_2: ${USER_ID_2} # only for portfolio demo
            USER_ID_3: ${USER_ID_3} # only for portfolio demo
        restart: on-failure
        expose:
            - "3306"

    phpmyadmin:
        image: phpmyadmin:5.2.1
        container_name: phpmyadmin
        env_file: .env
        volumes:
            - mysql_volume:/var/lib/mysql
        networks:
            - camagru-network
        ports:
            - 8002:80
        depends_on:
            - mysql
        restart: on-failure

volumes:
    mysql_volume:

networks:
    camagru-network:
        driver: bridge